"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { InvoiceData } from "./invoice-utils";
import { UserRole } from "./auth-context";
import { REAL_CUSTOMERS, REAL_PRODUCTS } from "./real-data";
import { useCompany } from "./company-context";

export interface StoredInvoice extends InvoiceData {
    id: string; // Unique ID for finding in DB
    generatedBy: {
        name: string;
        role: UserRole;
    };
    generatedAt: {
        date: string;
        time: string;
        location?: string;
    };
    status: 'GENERATED' | 'PRINTED' | 'DISPATCHED' | 'DELIVERED' | 'PAID' | 'PENDING' | 'CANCELLED';
    totalAmount: number;
}

export interface InvoiceNotification {
    id: string;
    message: string;
    invoiceId: string;
    timestamp: number;
    read: boolean;
    targetRoles: UserRole[]; // Roles that should see this
}

interface InvoiceContextType {
    invoices: StoredInvoice[];
    notifications: InvoiceNotification[];
    addInvoice: (invoiceData: InvoiceData, user: { name: string, role: UserRole, employeeId?: string | null }, location?: string) => void;
    markNotificationRead: (id: string) => void;
    getPendingInvoices: () => StoredInvoice[];
    updateInvoiceStatus: (id: string, status: any) => void;
}

const InvoiceContext = createContext<InvoiceContextType | undefined>(undefined);

export function InvoiceProvider({ children }: { children: React.ReactNode }) {
    const { currentCompany } = useCompany();
    const [invoices, setInvoices] = useState<StoredInvoice[]>([]);
    const [notifications, setNotifications] = useState<InvoiceNotification[]>([]);

    useEffect(() => {
        const fetchInvoices = async () => {
            try {
                // Fetch from Server Action
                const { getAnalyticsData } = await import("@/actions/invoice");
                const { invoices: dbInvoices } = await getAnalyticsData('7d', currentCompany);

                const mappedInvoices: StoredInvoice[] = dbInvoices.map((inv: any) => ({
                    ...inv,
                    date: new Date(inv.date).toISOString().split('T')[0],
                    customer: JSON.parse(inv.customerDetails),
                    items: inv.items.map((item: any) => ({
                        id: item.productId,
                        description: item.description,
                        quantity: item.quantity,
                        price: item.price,
                        costPrice: item.costPrice,
                        hsn: item.hsn,
                        gstRate: 18 // Default
                    })),
                    generatedBy: { name: "System", role: "ADMIN" }, // Placeholder
                    generatedAt: { date: new Date(inv.createdAt).toLocaleDateString(), time: "", location: "" },
                    status: inv.status
                }));

                setInvoices(mappedInvoices);
            } catch (err) {
                console.error("Failed to load invoices", err);
            }
        };
        fetchInvoices();
    }, [currentCompany]);

    const addInvoice = async (invoiceData: InvoiceData, user: { name: string, role: UserRole, employeeId?: string | null }, location = "Unknown Location") => {
        // Optimistic Update
        const newInvoice: StoredInvoice = {
            ...invoiceData,
            id: invoiceData.invoiceNo,
            generatedBy: user,
            generatedAt: {
                date: new Date().toLocaleDateString(),
                time: new Date().toLocaleTimeString(),
                location: location
            },
            status: invoiceData.status || 'PENDING',
            totalAmount: invoiceData.items.reduce((acc, item) => item.quantity * item.price, 0) // Simplify for now
        };

        setInvoices(prev => [newInvoice, ...prev]);

        // Persist to DB
        const { createInvoiceAction } = await import("@/actions/invoice");
        const result = await createInvoiceAction({
            ...invoiceData,
            employeeId: user.employeeId || undefined,
            companyName: currentCompany
        });

        // Create Notification
        const newNotification: InvoiceNotification = {
            id: Date.now().toString(),
            message: `New Invoice ${newInvoice.invoiceNo} generated by ${user.role} (${user.name}) at ${location}.`,
            invoiceId: newInvoice.id,
            timestamp: Date.now(),
            read: false,
            targetRoles: ["ADMIN", "EMPLOYEE", "DRIVER", "FIELD_WORKER"]
        };

        setNotifications(prev => [newNotification, ...prev]);
    };

    const markNotificationRead = (id: string) => {
        setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));
    };

    const getPendingInvoices = () => {
        return invoices.filter(i => i.status === 'GENERATED' || i.status === 'PRINTED' || i.status === 'PENDING');
    };

    const updateInvoiceStatus = (id: string, status: any) => {
        setInvoices(prev => prev.map(inv => inv.invoiceNo === id || inv.id === id ? { ...inv, status } : inv));
    };

    return (
        <InvoiceContext.Provider value={{ invoices, notifications, addInvoice, markNotificationRead, getPendingInvoices, updateInvoiceStatus }}>
            {children}
        </InvoiceContext.Provider>
    );
}

export function useInvoice() {
    const context = useContext(InvoiceContext);
    if (context === undefined) {
        throw new Error("useInvoice must be used within an InvoiceProvider");
    }
    return context;
}
