export function getWhatsAppUrl(text: string, phone?: string) {
    const encodedText = encodeURIComponent(text);
    if (phone) {
        return `https://wa.me/${phone}?text=${encodedText}`;
    }
    return `https://wa.me/?text=${encodedText}`;
}

export function shareReportOnWhatsApp(reportTitle: string, data: any, phoneNumber?: string) {
    const text = `*SmartVyapar Report*\n\n*Report:* ${reportTitle}\n*Date:* ${new Date().toLocaleDateString()}\n\n*Summary:*\n${Object.entries(data).map(([k, v]) => `- ${k}: ${v}`).join('\n')}\n\n_Generated by SmartVyapar AI OS_`;
    window.open(getWhatsAppUrl(text, phoneNumber), '_blank');
}
