export function getWhatsAppUrl(text: string, phone?: string) {
    const encodedText = encodeURIComponent(text);
    if (phone) {
        const normalized = phone.replace(/\D/g, '');
        const withCountry = normalized.length <= 10 ? `91${normalized}` : normalized;
        return `https://wa.me/${withCountry}?text=${encodedText}`;
    }
    return `https://wa.me/?text=${encodedText}`;
}

export function shareViaWhatsApp(text: string, phone?: string) {
    if (typeof window === 'undefined') return;
    window.open(getWhatsAppUrl(text, phone), '_blank');
}

export function shareReportOnWhatsApp(reportTitle: string, data: any, phoneNumber?: string) {
    const text = `*SmartVyapar Report*\n\n*Report:* ${reportTitle}\n*Date:* ${new Date().toLocaleDateString()}\n\n*Summary:*\n${Object.entries(data).map(([k, v]) => `- ${k}: ${v}`).join('\n')}\n\n_Generated by SmartVyapar AI OS_`;
    shareViaWhatsApp(text, phoneNumber);
}

export function shareSitePhotosViaWhatsApp(opts: {
    user?: string;
    address?: string;
    timestamp?: string | Date;
    stockSnapshot?: { name: string; qty: number }[];
    phone?: string;
}) {
    const lines = ['*SmartVyapar — Site Photo*'];
    if (opts.user) lines.push(`👤 ${opts.user}`);
    if (opts.address) lines.push(`📍 ${opts.address}`);
    if (opts.timestamp) {
        const d = typeof opts.timestamp === 'string' ? new Date(opts.timestamp) : opts.timestamp;
        lines.push(`🕐 ${d.toLocaleString()}`);
    }
    if (opts.stockSnapshot && opts.stockSnapshot.length > 0) {
        lines.push('\n*Stock snapshot:*');
        opts.stockSnapshot.forEach((s) => lines.push(`• ${s.name} × ${s.qty}`));
    }
    lines.push('\n_Sent via SmartVyapar_');
    shareViaWhatsApp(lines.join('\n'), opts.phone);
}

// ============================================
// INVOICE REMINDER SHARING
// ============================================

export interface InvoiceReminderData {
    invoiceNo: string;
    invoiceDate: string | Date;
    customerName: string;
    totalAmount: number;
    paidAmount?: number;
    balance?: number;
    dueDate?: string | Date;
    daysPastDue?: number;
    items: { description: string; quantity: number; price: number }[];
    outstandingBalance?: number;
    companyName: string;
    companyPhone?: string;
}

/**
 * Format currency in Indian format
 */
function formatCurrency(amount: number): string {
    return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR',
        maximumFractionDigits: 0,
    }).format(amount);
}

/**
 * Format date in readable format
 */
function formatDateStr(date: string | Date): string {
    const d = typeof date === 'string' ? new Date(date) : date;
    return new Intl.DateTimeFormat('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
    }).format(d);
}

/**
 * Share invoice payment reminder via WhatsApp
 */
export function shareInvoiceReminderViaWhatsApp(
    data: InvoiceReminderData,
    phone?: string
): void {
    const itemsList = data.items
        .map((item) => `• ${item.description} (${item.quantity} × ${formatCurrency(item.price)})`)
        .join('\n');

    const balance = data.balance ?? (data.totalAmount - (data.paidAmount ?? 0));

    const lines = [
        `Dear ${data.customerName},`,
        '',
        'This is a reminder regarding your pending payment.',
        '',
        '*Invoice Details:*',
        `📄 Invoice No: ${data.invoiceNo}`,
        `📅 Date: ${formatDateStr(data.invoiceDate)}`,
        `💰 Amount: ${formatCurrency(data.totalAmount)}`,
    ];

    if (data.paidAmount && data.paidAmount > 0) {
        lines.push(`✅ Paid: ${formatCurrency(data.paidAmount)}`);
    }

    lines.push(`⏳ *Balance Due: ${formatCurrency(balance)}*`);

    if (data.dueDate) {
        lines.push(`📆 Due Date: ${formatDateStr(data.dueDate)}`);
    }

    if (data.daysPastDue && data.daysPastDue > 0) {
        lines.push(`⚠️ Days Overdue: ${data.daysPastDue}`);
    }

    lines.push('', '*Items:*', itemsList);

    if (data.outstandingBalance && data.outstandingBalance !== balance) {
        lines.push('', `*Total Outstanding: ${formatCurrency(data.outstandingBalance)}*`);
    }

    lines.push(
        '',
        'Please make the payment at your earliest convenience.',
        '',
        'Regards,',
        data.companyName
    );

    if (data.companyPhone) {
        lines.push(`📞 ${data.companyPhone}`);
    }

    shareViaWhatsApp(lines.join('\n'), phone);
}

/**
 * Share a pre-generated reminder message via WhatsApp
 */
export function shareReminderMessageViaWhatsApp(message: string, phone?: string): void {
    shareViaWhatsApp(message, phone);
}

/** Derive a sensible .pdf filename from our uploaded URL path. */
export function filenameFromPdfUrl(pdfUrl: string, fallback = "invoice.pdf"): string {
    try {
        const path = new URL(pdfUrl, typeof window !== "undefined" ? window.location.origin : "http://localhost").pathname;
        const base = path.split("/").pop();
        if (base && /\.pdf$/i.test(base)) return decodeURIComponent(base);
    } catch {
        /* ignore */
    }
    return fallback.endsWith(".pdf") ? fallback : `${fallback}.pdf`;
}

/**
 * Save the PDF to the user’s Downloads folder so they can attach it in WhatsApp.
 * Falls back to opening the URL in a new tab if fetch fails (e.g. cross-origin).
 */
export async function downloadPdfFromUrl(pdfUrl: string, filename?: string): Promise<void> {
    if (typeof window === "undefined") return;
    const name = filename || filenameFromPdfUrl(pdfUrl);
    try {
        // Prefer same-site relative path so localhost vs 127.0.0.1 still works.
        let reqUrl = pdfUrl;
        try {
            const parsed = new URL(pdfUrl, window.location.href);
            if (parsed.pathname.startsWith("/")) {
                reqUrl = `${parsed.pathname}${parsed.search}`;
            }
        } catch {
            /* use pdfUrl as-is */
        }
        const res = await fetch(reqUrl, { credentials: "same-origin" });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const blob = await res.blob();
        const objectUrl = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = objectUrl;
        a.download = name;
        a.rel = "noopener";
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(objectUrl);
    } catch (e) {
        console.error("downloadPdfFromUrl:", e);
        window.open(pdfUrl, "_blank", "noopener,noreferrer");
    }
}
