
const fs = require('fs');
const path = require('path');

const inputPath = '/Users/pranavprabumurugan/.gemini/antigravity/brain/7aa46aed-38ba-4c8b-a788-5b196790f138/walkthrough.md';
const outputPath = path.join(process.cwd(), 'SmartVyapar_Report.html');

try {
    let markdown = fs.readFileSync(inputPath, 'utf8');

    // Simple Markdown to HTML conversion
    let htmlContent = markdown
        // Headers
        .replace(/^# (.*$)/gim, '<h1>$1</h1>')
        .replace(/^## (.*$)/gim, '<h2>$1</h2>')
        .replace(/^### (.*$)/gim, '<h3>$1</h3>')
        // Bold
        .replace(/\*\*(.*)\*\*/gim, '<b>$1</b>')
        // Italic
        .replace(/\*(.*)\*/gim, '<i>$1</i>')
        // Images (Simple)
        .replace(/!\[(.*?)\]\((.*?)\)/gim, (match, alt, src) => {
            // Check if src is absolute path and convert to file:// if needed or base64?
            // Browsers block local file access from http usually, but if opened as file it works.
            // Let's keep absolute path but clean it if needed.
            // But wait, carousel uses custom syntax.
            return `<div class="image-container"><img src="${src}" alt="${alt}"><p class="caption">${alt}</p></div>`;
        })
        // Carousel cleaning
        .replace(/````carousel/g, '<div class="carousel-print">')
        .replace(/````/g, '</div>')
        .replace(/<!-- slide -->/g, '')
        // Lists
        .replace(/^\d+\. (.*$)/gim, '<li>$1</li>') // Ordered list items (simplistic, doesn't wrap in ol)
        .replace(/^- (.*$)/gim, '<li>$1</li>') // Unordered list items
        // Horizontal Rules
        .replace(/^---/gim, '<hr>')
        // Tables (very basic support regex, might be cleaner to just wrap in pre if complex)
        .replace(/\|(.*)\|/gim, '<tr><td>$1</td></tr>') // Very rough table row
        // Blockquotes/Alerts
        .replace(/> \[\!NOTE\]/g, '<strong>NOTE:</strong>')
        .replace(/> \[\!TIP\]/g, '<strong>TIP:</strong>')
        .replace(/> (.*)/g, '<blockquote class="alert">$1</blockquote>');

    // Wrap lists (rough) - regex is hard for nested lists, let's just make it readable.

    const fullHtml = `
<!DOCTYPE html>
<html>
<head>
    <title>SmartVyapar Deployment Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 20px; color: #333; }
        h1 { border-bottom: 2px solid #333; padding-bottom: 10px; color: #111; }
        h2 { color: #222; margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        h3 { color: #444; margin-top: 20px; }
        img { max-width: 100%; border: 1px solid #ddd; border-radius: 4px; margin: 10px 0; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        .image-container { text-align: center; margin: 20px 0; page-break-inside: avoid; }
        .caption { font-size: 0.9em; color: #666; font-style: italic; margin-top: 5px; }
        code { background: #f4f4f4; padding: 2px 5px; border-radius: 3px; font-family: "Courier New", Courier, monospace; }
        blockquote { border-left: 4px solid #0070f3; margin: 15px 0; padding: 10px 20px; background: #f0f7ff; color: #0056b3; }
        li { margin-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        td, th { border: 1px solid #ddd; padding: 8px; text-align: left; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        @media print {
            body { max-width: none; margin: 0; padding: 20px; }
            .no-print { display: none; }
            h2 { page-break-before: always; } /* Start new sections on new pages */
            h1, h2, h3 { page-break-after: avoid; }
            img { max-width: 100% !important; }
        }
    </style>
</head>
<body>
    <div style="text-align: center; margin-bottom: 50px;">
        <h1 style="border:none;">SmartVyapar Project Report</h1>
        <p><strong>Generated on:</strong> ${new Date().toLocaleString()}</p>
        <p><strong>Status:</strong> Deployment & Verification Complete</p>
    </div>
    ${htmlContent}
    <div style="margin-top: 50px; text-align: center; font-size: 0.8em; color: #888;">
        Generated by Antigravity Agent
    </div>
</body>
</html>
    `;

    fs.writeFileSync(outputPath, fullHtml);
    console.log(`Report generated at: ${outputPath}`);

} catch (err) {
    console.error('Error generating report:', err);
}
